using DlssMfgManager.Models;

namespace DlssMfgManager.Services;

public static class CompatibilityCatalog
{
    public const string UpstreamProjectUrl = "https://github.com/sdli1995/dlssg_for_sm86";
    public const string NvidiaGamesUrl = "https://www.nvidia.com/en-us/geforce/technologies/dlss/";

    public static IReadOnlyList<SupportedGpu> SupportedGpus { get; } =
    [
        new("RTX 20 · SM75", "GeForce RTX 2060", "Desktop"),
        new("RTX 20 · SM75", "GeForce RTX 2060 SUPER", "Desktop"),
        new("RTX 20 · SM75", "GeForce RTX 2070", "Desktop"),
        new("RTX 20 · SM75", "GeForce RTX 2070 SUPER", "Desktop"),
        new("RTX 20 · SM75", "GeForce RTX 2080", "Desktop"),
        new("RTX 20 · SM75", "GeForce RTX 2080 SUPER", "Desktop"),
        new("RTX 20 · SM75", "GeForce RTX 2080 Ti", "Desktop"),
        new("RTX 20 · SM75", "GeForce RTX 2060 Laptop GPU", "Laptop"),
        new("RTX 20 · SM75", "GeForce RTX 2070 / 2070 SUPER Laptop GPU", "Laptop / Max-Q"),
        new("RTX 20 · SM75", "GeForce RTX 2080 / 2080 SUPER Laptop GPU", "Laptop / Max-Q"),

        new("RTX 30 · SM86", "GeForce RTX 3050", "Desktop"),
        new("RTX 30 · SM86", "GeForce RTX 3060", "Desktop"),
        new("RTX 30 · SM86", "GeForce RTX 3060 Ti", "Desktop"),
        new("RTX 30 · SM86", "GeForce RTX 3070", "Desktop"),
        new("RTX 30 · SM86", "GeForce RTX 3070 Ti", "Desktop"),
        new("RTX 30 · SM86", "GeForce RTX 3080", "Desktop"),
        new("RTX 30 · SM86", "GeForce RTX 3080 Ti", "Desktop"),
        new("RTX 30 · SM86", "GeForce RTX 3090", "Desktop"),
        new("RTX 30 · SM86", "GeForce RTX 3090 Ti", "Desktop"),
        new("RTX 30 · SM86", "GeForce RTX 3050 / 3050 Ti Laptop GPU", "Laptop"),
        new("RTX 30 · SM86", "GeForce RTX 3060 Laptop GPU", "Laptop"),
        new("RTX 30 · SM86", "GeForce RTX 3070 / 3070 Ti Laptop GPU", "Laptop"),
        new("RTX 30 · SM86", "GeForce RTX 3080 / 3080 Ti Laptop GPU", "Laptop")
    ];

    // Offline snapshot of games with an NVIDIA DLSS Frame Generation or Multi Frame Generation integration.
    // The catalogue is deliberately advisory: game patches, plugins and anti-cheat policies can change.
    public static IReadOnlyList<string> FrameGenerationGames { get; } = new[]
    {
        "A Plague Tale: Requiem",
        "A Quiet Place: The Road Ahead",
        "Akimbot",
        "Alan Wake 2",
        "Ambulance Life: A Paramedic Simulator",
        "Assassin's Creed Shadows",
        "Assassin's Creed Black Flag Resynced",
        "Atomic Heart",
        "Aunt Fatima",
        "Avatar: Frontiers of Pandora",
        "Avowed",
        "Backrooms: Escape Together",
        "Bears In Space",
        "Bellwright",
        "Black Myth: Wukong",
        "Bright Memory: Infinite",
        "Code Alkonost: Awakening of Evil",
        "Crown Simulator - Royal Life Simulation",
        "Cyberpunk 2077",
        "Deceit 2",
        "Deep Rock Galactic",
        "Deliver Us Mars",
        "Delta Force: Black Hawk Down",
        "DESORDRE: A Puzzle Game Adventure",
        "Desynced: Autonomous Colony Simulator",
        "Diablo IV",
        "DIRECT CONTACT",
        "Dragon Age: The Veilguard",
        "Dragon's Dogma 2",
        "Dungeonborne",
        "DYNASTY WARRIORS: ORIGINS",
        "Enlisted",
        "Eternal Strands",
        "EVE Frontier",
        "EVERSPACE 2",
        "F1 22",
        "F1 23",
        "F1 24",
        "F1 25",
        "FINAL FANTASY XVI",
        "Flintlock: The Siege of Dawn",
        "Fort Solis",
        "Forza Horizon 5",
        "Forza Motorsport",
        "FragPunk",
        "Frostpunk 2",
        "Ghost of Tsushima Director's Cut",
        "Ghostrunner 2",
        "God of War Ragnarök",
        "Gray Zone Warfare",
        "GROUND BRANCH",
        "Half-Life 2 RTX Demo",
        "Half Sword",
        "HITMAN World of Assassination",
        "Hogwarts Legacy",
        "ICARUS",
        "Immortals of Aveum",
        "Indiana Jones and the Great Circle",
        "Jusant",
        "JX3 Online RTX Version",
        "Kristala",
        "Layers of Fear (2023)",
        "Legacy: Steel & Sorcery",
        "LEGO Horizon Adventures",
        "Liminalcore",
        "Lords of the Fallen",
        "Lost Records: Bloom & Rage",
        "Marvel Rivals",
        "Marvel's Spider-Man 2",
        "Marvel's Spider-Man: Miles Morales",
        "Marvel's Spider-Man Remastered",
        "Mecha BREAK",
        "Microsoft Flight Simulator 40th Anniversary Edition",
        "Microsoft Flight Simulator 2024",
        "Mortal Online 2",
        "NARAKA: BLADEPOINT",
        "Need for Speed Unbound",
        "Nightingale",
        "NINJA GAIDEN 2 Black",
        "No More Room in Hell 2",
        "Once Human",
        "Outpost: Infinity Siege",
        "Pax Dei",
        "Payday 3",
        "Portal with RTX",
        "POSTAL 4: No Regerts",
        "QANGA",
        "Ratchet & Clank: Rift Apart",
        "Ready or Not",
        "Redfall",
        "REMNANT II",
        "Returnal",
        "Rise of the Ronin",
        "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
        "Satisfactory",
        "SCUM",
        "Senua's Saga: Hellblade II",
        "Serum",
        "SILENT HILL 2",
        "Skye: The Misty Isle",
        "Slender: The Arrival",
        "SMITE 2",
        "Squad",
        "Star Wars Jedi: Survivor",
        "Star Wars Outlaws",
        "Starfield",
        "Starship Troopers: Extermination",
        "Still Wakes the Deep",
        "Stormgate",
        "TankHead",
        "Test Drive Unlimited Solar Crown",
        "The Axis Unseen",
        "The Black Pool",
        "The Finals",
        "The First Berserker: Khazan",
        "The First Descendant",
        "The Thaumaturge",
        "The Witcher 3: Wild Hunt",
        "Tokyo Xtreme Racer",
        "Torque Drift 2",
        "TRIBES 3: Rivals",
        "Until Dawn",
        "Vector Strike",
        "Warhammer 40,000: Darktide",
        "Warhammer 40,000: Space Marine 2",
        "Witchfire",
        "World of Jade Dynasty"
    }
    .Distinct(StringComparer.OrdinalIgnoreCase)
    .OrderBy(name => name, StringComparer.CurrentCultureIgnoreCase)
    .ToArray();
}
